### ISSUE TITLE
Packaging pelican-deadlinks for PyPi distribution.

### ISSUE THREAD

**Issue by kdeldycke** [silentlamb/pelican-deadlinks#8]
Since Pelican 4.5, plugins can be distributed as independent python package and published to PyPi.

The community is working hard splitting out the https://github.com/getpelican/pelican-plugins mono-repo to the new https://github.com/getpelican/pelican-plugins umbrella organization. I already did some work to migrate the `neighbors` to its own repo: https://github.com/pelican-plugins/neighbors/pull/2

Can I assist in any capacity to package up the `pelican-deadlinks` plugin? 🙂

**Comment by silentlamb** [comment]
@kdeldycke Hi Kevin! I am really sorry to say that I am no longer interested in development of this plugin. I've written it for my own needs and decided to share it with others without realization that this repository would require maintanance from me (my first open-source contribution). 

I also don't want to hold any pelican-plugins' issues because of my plugin. If you think the plugin is worth keeping, I'd be more than happy to make it move from my external repository to just a subfolder. Maybe this way someone decided to improve it and continue development of it.

**Comment by kdeldycke** [comment]
Thanks @silentlamb for the reply!

I totally understand your current position, maintaining open-source components might ends up being really time-consuming and excruciating at times. And it is totally normal to lost interest after a while. I myself somewhat surprised how some of my (very) old stuff still get an audience.

That being said, thanks a lot for allowing the continuation of that project. The next phase consist in transferring the ownership to the [`pelican-plugins` organization](https://github.com/getpelican/pelican-plugins). I still not have enough permissions to help with that.

So the next steps are:
1. Kindly ask for @justinmayer or @avaris (👋) to temporarily grant you permission for repository transfer (like [we did last month with `similar-posts` plugin](https://github.com/pelican-plugins/similar-posts/issues/3#issuecomment-696347147))
2. For you to perform the transfer of the repository. Should be easy: see the red `Transfer` button at the bottom of your repo settings: https://github.com/silentlamb/pelican-deadlinks/settings
3. Let the community (me, likely 😅) properly package the plugin to be distributable to PyPi.

**Comment by kdeldycke** [comment]
Now that I'm thinking of it, @silentlamb , you can add @justinmayer or @avaris as admin to this repository so they can transfer the project to its new `pelican-plugins` home. What do you think?

**Comment by justinmayer** [comment]
> you can add @justinmayer or @avaris as admin to this repository so they can transfer the project to its new `pelican-plugins` home. What do you think?

That would actually be the easiest way to do this. If you would be so kind as to add me (`justinmayer`) with Admin role, I'd be happy to manage the plugin's relocation to the Pelican Plugins organization. You can do that here: https://github.com/silentlamb/pelican-deadlinks/settings/access

Thank you, Marcin! 💫

**Comment by silentlamb** [comment]
Hello! 

I couldn't find any admin access persmissions on that page, only an "add collaborator" action so I've send @justinmayer the request.  If that's not enough then I'm happy to help and resolve this issue as finally I got some spare time for github. Just let me know.

**Comment by Jalict** [comment]
Mainly bumping this; but I am super curious to hear if this landed somewhere?

**Comment by justinmayer** [comment]
Hi @Jalict. Not yet. But I'd like to rectify that, so I just now temporarily invited @silentlamb to join the Pelican Plugins organization.

@silentlamb: Once you accept that invitation, you should be able to initiate the transfer to the Pelican Plugins organization. Once the transfer is complete, I will set the permissions so you have full maintainer access to the project at its new home. 😊 

I'm sorry that GitHub's process for this is a bit cumbersome.

Does that make sense? Please let me know if you have any questions or if you need assistance!

**Comment by silentlamb** [comment]
I think the transfer is finished. Thanks!

**Comment by justinmayer** [comment]
It does indeed seem like the transfer is complete. Thanks, Marcin!

@kdeldycke: Any chance you'd like to assist with migrating this plugin to resemble what would be generated via the current Cookiecutter template?

**Comment by kdeldycke** [comment]
Thanks @justinmayer for the update! Will try to integrate it into my broken blog ahah
